<?php

/**
 * @file
 * Primary module hooks for spaker_mod module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
/**
* Implements hook_theme().
*/

function spaker_mod_theme() {
    // pre-formatage et template pour le menu.
    $hooks['layoutmenu_vesperr_header_menu'] = [
      'render element' => 'element',
      'preprocess functions' => [
        'template_preprocess_layoutmenu_vesperr_header_menu'
      ],
      'file' => 'spaker_mod.theme.inc'
    ];
    return $hooks;
  }